import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Tutor Nexus Sidebars Configuration
 * 
 * Three main sections:
 * - Guides: Getting started, development, deployment
 * - Reference: API docs, features
 * - Architecture: ADRs (Architecture Decision Records)
 * 
 * Using autogenerated sidebars for each directory.
 * Files are sorted by sidebar_position in frontmatter.
 */
const sidebars: SidebarsConfig = {
  // Guides sidebar - autogenerated from guides/ directory
  guidesSidebar: [
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'guides' }],
    },
  ],

  // Reference sidebar - autogenerated from reference/ directory
  referenceSidebar: [
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'reference' }],
    },
  ],

  // Architecture Decision Records sidebar - autogenerated from adrs/ directory
  adrsSidebar: [
    {
      type: 'category',
      label: 'Architecture',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Architecture Decision Records',
        description: 'Documentation of key architectural decisions made for Tutor Nexus.',
        slug: '/adrs',
      },
      items: [{ type: 'autogenerated', dirName: 'adrs' }],
    },
  ],
};

export default sidebars;
